version: "3"

services:
        papermc:
                build: .
                command: java -Xms2g -Xmx3G -jar lightweight_server/paper-220.jar
                volumes:
                        - '.:/lightweight_server'
                ports:
                        - "25565:25565"
